name: CI
on: pull_request
jobs:
  code-quality:
    name: Check the code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run eslint
        run: npm run lintnew
      - name: Run lit-analyzer
        run: npm run lint:lit-analyzer
        continue-on-error: true
      - name: Run tests
        run: npm run test
  deploy-preview:
     name: Deploy preview version of the storybook on firebase
     needs: [code-quality]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Setup node
         uses: actions/setup-node@v3
         with:
           node-version: 18.x.x
           cache: 'npm'
       - name: Install dependencies
         run: npm ci
       - name: Build storybook
         run: npm run build-storybook
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
           firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZETA_DS }}"
