name: Create documentation links on Figma

on: workflow_dispatch

jobs:
  link-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: "yarn" Removed due to https://github.com/actions/setup-node/issues/1027

      - name: Yarn install
        run: yarn install --immutable

      - name: Create custom-elements.json
        run: yarn run analyze

      - name: Create documentation links
        uses: ./.github/workflows/link-docs
        with:
          figma-access-token: ${{ secrets.FIGMA_TOKEN }}
