name: CI - On Release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zebratechnologies',
              repo: 'zeta',
              workflow_id: 'deploy.yml',
              ref: 'main', 
            })

  publish-web:
    uses: ./.github/workflows/publish-web.yml
    secrets: inherit
