name: CI - On Release

on:
  release:
    types: [released]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zebratechnologies',
              repo: 'design.zebra.com',
              workflow_id: 'deploy.yml',
              ref: 'main', 
              inputs:{
                package_to_update: 'zeta-web',
              }
            })

  publish-web:
    environment: npmjs.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: "yarn" Removed due to https://github.com/actions/setup-node/issues/1027
      - name: Inject auth token
        run: |
          echo npmAuthToken: "${{secrets.NPM_TOKEN}}" >> ./.yarnrc.yml

      - name: Install packages
        run: yarn install --immutable

      - name: Compile Typescript files
        run: yarn run build

      - name: Publish
        run: yarn npm publish
